// Portfolio content, single source of truth
window.PORTFOLIO_DATA = {
  name: "Shanmukha Chatadi",
  role: "Applied AI/ML Engineer",
  location: "Raleigh, NC",
  status: "Open to opportunities",
  tagline: "I build agentic AI systems, production LLM pipelines, and the scalable cloud plumbing that keeps them honest.",
  images: {
    hero: "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=2400&q=80",
    nebula: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=2400&q=80",
    data: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=2400&q=80",
    grid: "https://images.unsplash.com/photo-1451187863213-d1bcbaae3fa3?w=2400&q=80",
    terminal: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=2400&q=80",
    abstract: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=2400&q=80",
    neural: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=2400&q=80",
    portrait: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600&q=80",
  },
  currently: {
    role: "AI Research Intern",
    company: "MiHIN",
    project: "Document AI / RAG platform on AWS Bedrock",
    since: "Aug 2025"
  },
  stats: [
    { n: "1.5+", label: "Years Industry" },
    { n: "10+", label: "Projects Shipped" },
    { n: "2", label: "Publications" },
    { n: "230+", label: "Users Served" },
  ],
  experience: [
    {
      company: "MiHIN",
      role: "AI Research Intern",
      location: "Michigan Health Information Network · Lansing, MI",
      period: "Aug 2025 — Present",
      short: "Architecting a production Document AI / RAG platform on AWS Bedrock, serving 230+ employees over 1TB+ of enterprise documents at 75% lower cost.",
      bullets: [
        "Architected production Document AI / RAG platform on AWS Bedrock, OpenSearch Serverless, Pinecone, and Lambda, enabling 230+ employees to query 1TB+ enterprise documents at 75% lower cost.",
        "Engineered NLP retrieval pipeline with document parsing, Titan V2 embeddings, configurable chunking, and Claude Sonnet via Bedrock; iterated on chunking and retrieval-K with human-in-the-loop feedback, cutting ungrounded LLM responses by 30%.",
        "Integrated AI workflows through secure REST APIs with API Gateway, Lambda, and Cognito (SSO + MFA + audit logging) enforcing PHI access controls; instrumented CloudWatch dashboards, alarms, and dead-letter routing, reducing mean time to detection by 60%.",
        "Partnered with DevOps, Legal, HR, and business stakeholders to translate enterprise requirements into AI governance playbooks aligned with HITRUST CSF, NIST, and HIPAA; led AI Task Force training enabling 5+ teams to deploy generative AI.",
      ],
      tags: ["AWS Bedrock", "RAG", "OpenSearch", "Pinecone", "Lambda", "Claude Sonnet", "Cognito", "CloudWatch", "HITRUST"],
    },
    {
      company: "Rygen BioPharma",
      role: "Software Engineer",
      location: "Hyderabad, India",
      period: "Mar 2023 — Aug 2024",
      short: "Built full-stack tooling and data pipelines that ran the day-to-day for four research teams.",
      bullets: [
        "Built full-stack platform with Flask, React, and PostgreSQL backed by REST APIs for 4+ research teams, cutting manual reporting time by 40%.",
        "Built Python ETL pipelines (Pandas, NumPy) processing 100K+ records daily with PostgreSQL triggers; cut data errors by 50%.",
        "Shipped Dockerized microservices to AWS with Jenkins CI/CD; wrote 200+ unit and integration tests at 85%+ coverage, cutting release cycles from 2 days to under 3 hours.",
        "Automated weekly R&D reporting with Python, Pandas, scikit-learn, and Power BI dashboards; replaced manual Excel workflows with scheduled pipelines, saving researchers 10+ hours per week.",
      ],
      tags: ["Python", "Flask", "React", "PostgreSQL", "Pandas", "Docker", "Jenkins", "AWS", "Power BI"],
    },
    {
      company: "TreoSoft IT Solutions",
      role: "Data Science Intern",
      location: "Bengaluru, India",
      period: "Jun 2022 — Sep 2022",
      short: "Shipped a product-bundling recommender that lifted client net sales by 15%.",
      bullets: [
        "Shipped FP-Growth product-bundling system with Flask REST APIs and PostgreSQL; mined association rules on 100K+ transactions, surfacing top co-purchase bundles and driving a 15% net sales increase.",
        "Built EDA in Python (Pandas, NumPy, Matplotlib) over client transaction data; surfaced top co-purchase pairs and recommended price-anchored bundle offers for client rollout.",
      ],
      tags: ["Python", "FP-Growth", "Flask", "PostgreSQL", "Pandas", "Matplotlib"],
    },
  ],
  projects: [
    {
      n: "01",
      title: "ScholarAgent",
      subtitle: "Multi-Agent Research Assistant",
      year: "Jan — Mar 2025",
      tagline: "A LangGraph pipeline that reads 10K+ papers, grades its own answers, and refuses to hallucinate.",
      problem: "Most research copilots either retrieve and pray, or generate and hallucinate. I wanted something that could catch itself being wrong.",
      approach: "7-node LangGraph state machine, router, retriever, grader, rewriter, generator, hallucination-check, responder. ChromaDB over 10K+ arXiv/PubMed abstracts with HF sentence-transformer embeddings. Gemini does the final synthesis with citation spans.",
      impact: [
        "30% drop in unsupported claims vs. a plain RAG baseline",
        "Corrective RAG loop re-queries when grader fails, no silent failures",
        "Next.js + FastAPI UI streams responses with per-claim source links",
      ],
      tags: ["LangGraph", "ChromaDB", "Gemini", "FastAPI", "Next.js 14", "TypeScript"],
      href: "https://github.com/shinegami-2002/scholar-agent",
      image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=2000&q=80",
    },
    {
      n: "02",
      title: "MCP Healthcare Server",
      subtitle: "Model Context Protocol Server",
      year: "Feb — Mar 2025",
      tagline: "Six healthcare tools any MCP-compatible LLM can call, wired to four federal APIs.",
      problem: "Healthcare LLM apps re-implement the same wrappers around openFDA, PubMed, ClinicalTrials.gov, and NLM. I wanted one server that any MCP client could plug into.",
      approach: "FastMCP server exposing drug safety lookup, clinical trial search, ICD-10 resolution, PubMed search, drug-interaction checks, and medical term lookups. Async httpx with retries, schema validation on every response.",
      impact: [
        "Drop-in tool server for Claude / any MCP client, no custom glue per app",
        "Schema-validated responses, no garbage propagating to the LLM",
        "Fully typed, documented, and covered by integration tests",
      ],
      tags: ["Python", "FastMCP", "httpx", "openFDA", "PubMed", "NLM"],
      href: "https://github.com/shinegami-2002/mcp-healthcare-server",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=2000&q=80",
    },
    {
      n: "03",
      title: "LinkVault",
      subtitle: "Go REST API Platform",
      year: "Mar 2025",
      tagline: "A production-grade link-saving API. JWT,, rate limiting, Postgres FTS, all in idiomatic Go.",
      problem: "I wanted a sharper Go chops project that wasn't a toy, something with real auth, real caching, and real search.",
      approach: "Chi v5 router, dual auth (JWT for users + API keys for programmatic access), Redis-backed sliding-window rate limiter, Postgres full-text search with tsvector indexes. Dockerized, migrations handled via sql-migrate.",
      impact: [
        "Sub-50ms p95 on search over 100k synthetic links",
        "Zero-downtime migrations, structured logging, graceful shutdown",
        "End-to-end tests covering auth flows and rate-limit behavior",
      ],
      tags: ["Go", "Chi v5", "PostgreSQL", "Redis", "JWT", "Docker"],
      href: "https://github.com/shinegami-2002/linkvault",
      image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=2000&q=80",
    },
    {
      n: "04",
      title: "Distributed Task Queue",
      subtitle: "Go · gRPC · Kubernetes",
      year: "Feb — Mar 2025",
      tagline: "A Celery-style task queue built from scratch in Go, with real HPA, real Prometheus metrics, real Helm.",
      problem: "I wanted to understand distributed systems by building one, priority queueing, fanout, backpressure, autoscaling, not by reading about it.",
      approach: "gRPC + Protobuf service interface between producers / workers / dispatcher. Redis sorted sets as a priority queue. Postgres for durable state. Deployed on K8s with Helm charts; HPA scales workers on a custom Prometheus metric (queue depth).",
      impact: [
        "Workers scale up/down automatically as queue depth changes",
        "Priority + retry + dead-letter semantics, no dropped work",
        "Full observability: Prometheus metrics, structured logs, health probes",
      ],
      tags: ["Go", "gRPC", "Protobuf", "Redis", "PostgreSQL", "Kubernetes", "Helm"],
      href: "https://github.com/shinegami-2002/distributed-task-queue",
      image: "https://images.unsplash.com/photo-1506399558188-acca6f8cbf41?w=2000&q=80",
    },
    {
      n: "05",
      title: "Representational Fingerprinting in Pruned Networks",
      subtitle: "CSC 591/791 · NC State · Spring 2026",
      year: "Jan 2026 — Present",
      tagline: "Networks pruned to the same accuracy aren't the same network, and you can prove it from a single image.",
      problem: "Magnitude pruning is everywhere, but nobody asks what it actually changes inside a network when accuracy holds steady.",
      approach: "11 ResNet-18 configs on CIFAR-100 across a timing × ratio grid (30–97% sparsity) on 3× H100s, accuracy held within 1.48pp. Linear-CKA + 100K-permutation Mantel tests.",
      impact: [
        "Same accuracy, different network. CKA spread 0.73–0.95.",
        "CKA predicts shared mistakes at r=+0.95.",
        "Linear probe IDs pruning from one image at 89.2% (chance 25%).",
      ],
      tags: ["PyTorch", "ResNet-18", "CIFAR-100", "Linear CKA", "Mantel Test", "3× H100", "scikit-learn"],
      image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=2000&q=80",
    },
    {
      n: "06",
      title: "LLM-Driven Procedural Content Generation",
      subtitle: "LLMs4PCG Competition · AAAI 2026",
      year: "2025",
      tagline: "Using open-source LLMs to generate playable game levels, with a ViT as the judge.",
      problem: "Can small open-source LLMs generate procedurally-valid game content under constraints, and can we automate the validation?",
      approach: "Prompt-compiler pipeline across Phi-3, Gemma-2, and Qwen-2.5 with constraint satisfaction checks. Trained a ViT to score generated levels on playability and structure, feeding the signal back into generation.",
      impact: [
        "Competition-ready submission for LLMs4PCG @ AAAI 2026",
        "Model-agnostic prompt compiler, swappable backbones",
        "Automated ViT validator replaces manual level QA",
      ],
      tags: ["Phi-3", "Gemma-2", "Qwen-2.5", "Prompt Engineering", "ViT", "PCG"],
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=2000&q=80",
    },
    {
      n: "07",
      title: "AI ChatBot",
      subtitle: "Multi-Provider LLM Service",
      year: "Jan — Apr 2025",
      tagline: "A provider-agnostic chat backend, if one LLM goes down, the next one picks up.",
      problem: "Single-provider chat apps die when the provider dies. I wanted graceful failover across OpenAI, Groq, and friends.",
      approach: "FastAPI backend with LangChain orchestration, async APIs, circuit-breaker-style provider failover. Dockerized, Node.js frontend, Groq for low-latency default path.",
      impact: [
        "Transparent failover across providers, user never sees it",
        "Async pipeline keeps latency low under load",
        "Clean separation of provider adapters, add a new one in ~30 lines",
      ],
      tags: ["Python", "FastAPI", "LangChain", "Docker", "Node.js", "Groq"],
      href: "https://github.com/shinegami-2002/AI_ChatBot",
      image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=2000&q=80",
    },
  ],
  skills: {
    "AI / ML": ["RAG", "Agentic AI", "LLMs", "NLP", "Multi-Agent", "MCP", "Deep Learning", "Transformers", "Computer Vision", "MLOps", "HITL"],
    "Languages": ["Python", "TypeScript", "Go", "SQL", "C++", "Java", "Bash"],
    "Cloud & DevOps": ["AWS Bedrock", "Lambda", "API Gateway", "Cognito", "Docker", "Kubernetes", "GitHub Actions", "Jenkins"],
    "Frameworks": ["Next.js", "React", "FastAPI", "Flask", "Node.js", "Chi v5", "gRPC"],
    "Data": ["Postgres", "MongoDB", "Redis", "OpenSearch", "ChromaDB", "Vector DBs"],
    "Libraries": ["LangGraph", "LangChain", "PyTorch", "TensorFlow", "Hugging Face", "FastMCP", "Helm", "Prometheus"],
  },
  publications: [
    {
      title: "Potato Disease Classification Using Diverse Feature Extraction Methods and Machine Learning Models",
      authors: "C. Shanmukha Srinivas Sai et al.",
      venue: "HIS 2023 · Hybrid Intelligent Systems",
      publisher: "Springer",
      year: "2023",
    },
    {
      title: "Tea Leaf Disease Classification with Ensemble Stacking",
      authors: "Somesh K, C. Shanmukha Srinivas Sai et al.",
      venue: "ICDLAIR 2024",
      publisher: "IEEE",
      year: "2024",
    },
  ],
  education: [
    {
      school: "North Carolina State University",
      degree: "MS Computer Science · Data Science Track",
      detail: "GPA 3.71 · Aug 2024 – Jun 2026",
      courses: ["Deep Learning", "Machine Learning", "Neural Networks", "Algorithms", "Software Engineering", "DBMS"],
    },
    {
      school: "National Institute of Technology Puducherry",
      degree: "BTech Computer Science & Engineering",
      detail: "GPA 8.48/10 · Dec 2020 – Mar 2024",
    },
  ],
  leadership: [
    { role: "President", org: "Rotaract Club, NIT Puducherry", period: "2022–2023", note: "10+ community events, blood donation camps, awareness campaigns." },
    { role: "Vice-President", org: "ACE (CS Association), NIT Puducherry", period: "2022–2023", note: "Workshops, hackathons, and industry talks." },
    { role: "Co-founder", org: "Zer01Coded, NIT Puducherry", period: "2021–2022", note: "Founded coding club; taught Python to 150+ students." },
  ],
  achievements: [
    "First Position · Blind Coding Challenge, Gyanith Tech Fest (2023)",
    "Third Prize · Hackathon, NIE Mysore, ~90 competitors (2023)",
    "All India Rank 206 · Inter NIT Coding Marathon, MNIT Bhopal (2022)",
    "99.1 Percentile · JEE-Mains, top 1% of 1M+ students (2020)",
  ],
  hobbies: [
    { name: "Basketball", note: "Played competitively and won tournaments in college." },
    { name: "Astronomy", note: "Stargazing and following space missions." },
    { name: "Cyberpunk 2077", note: "A game that keeps pulling me back to Night City." },
    { name: "Origami", note: "Folding paper into intricate designs, surprisingly meditative." },
    { name: "Weightlifting", note: "Consistent gym-goer focused on strength training." },
    { name: "Teaching", note: "Taught Python to 150+ students through Zer01Coded." },
  ],
  contact: {
    email: "shanmukh.nitpy@gmail.com",
    linkedin: "linkedin.com/in/shanmukha-chatadi",
    github: "github.com/shinegami-2002",
  },
};
